version: '3'
name: esgame-container
services:
  #esgame-v2:
  #  image: esgame.azurecr.io/esgame:esgame-v2
  esgame-calculation:
    image: esgame.azurecr.io/esgame:esgame-calculation
    #ports:
    #  - "8000:8000"
  esgame-geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    environment:
      - CORS_ENABLED
    #ports:
    #  - "8080:8080"